[package]
name = "gym-bot-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frankenstein = "0.9.2"
log = "0.4"
dashmap = "5.0.0"
simple_logger ="1.16.0"
chrono = "0.4.19"
